spring:
  datasource:
    url: jdbc:log4jdbc:mysql://mini.cxwee6aeygsa.ap-northeast-2.rds.amazonaws.com/movie
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: admin
    password: admin1234

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  servlet:
    multipart:
      max-file-size: 1MB
    mvc:
      static-path-pattern: /webapp/**
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8099
  servlet:
    session:
      timeout: 1800

#logging:
#  level:
#    sql: trace

logging:
  level:
    org:
      springframework:
        jdbc: TRACE
        transaction: TRACE
    com:
      .zaxxer: TRACE
    sql: TRACE

cid: TC0ONETIME

kakaopay:
  api:
    secret:
      key: DEV24D1E9D44D9145F851EEEC95AAFE08F533B86

sample:
  host: http://localhost:8099



