spring:
  datasource:
    url: jdbc:log4jdbc:mysql://mini.cxwee6aeygsa.ap-northeast-2.rds.amazonaws.com/movie
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: admin
    password: admin1234

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  servlet:
    multipart:
      max-file-size: 1MB
    mvc:
      static-path-pattern: /webapp/**

server:
  port: 8098
  servlet:
    session:
      timeout: 1800

#logging:
#  level:
#    sql: trace

logging:
  level:
    org:
      springframework:
        jdbc: TRACE
        transaction: TRACE
    com:
      .zaxxer: TRACE
    sql: TRACE
