-- New script in cafe.
-- Date: 2024. 6. 20.
-- Time: 오후 7:34:42
--mini.cxwee6aeygsa.ap-northeast-2.rds.amazonaws.com                - target database host
--mini.cxwee6aeygsa.ap-northeast-2.rds.amazonaws.com         - tunnel host name
--3306                - target database port
--${server}              - target server name
--cafe            - target database name
--dkswl                - database user name
--jdbc:mysql://mini.cxwee6aeygsa.ap-northeast-2.rds.amazonaws.com:3306/cafe                 - connection URL
--dev     - connection type
--cafe          - datasource
--C:\Users\dkswl\OneDrive\Documents\code_upload\Auto_window\multi_it\backend\db\db1\General        - project path
--General        - project name
--2024. 6. 20.                - current date
--C:\Users\dkswl\OneDrive\Documents\code_upload\Auto_window\multi_it\backend\db\db1           - workspace path
--C:\Users\dkswl                - OS user home path
--C:\Users\dkswl\AppData\Local\DBeaver        - application install path
--C:\Users\dkswl\AppData\Local\DBeaver    - application install path
--DBeaver    - application name
--24.0.3.202404211624 - application version
--220.78.96.123            - local IP address
--2024. 6. 20.                - current date
--오후 7:34:42                - current time
--dkswl                - OS user name



CREATE TABLE `MEMBER` (
	`MEMBER_NO`	INT AUTO_INCREMENT PRIMARY KEY,
	`EMAIL`	VARCHAR(254)	NOT NULL UNIQUE,
	`PW`	VARCHAR(100)	NOT NULL,
	`USERNAME`	VARCHAR(50)	NOT NULL UNIQUE,
	`TEL`	VARCHAR(15)	NOT NULL,
	`IMG`	VARCHAR(100),
	`POINT`	INT	NOT NULL,
	`CRATE_DATE`	TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`MODFIY_DATE`	TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE `REGION` (
	`REGION_NO`	INT	AUTO_INCREMENT PRIMARY KEY,
	`REGION_NAME`	VARCHAR(30)	NOT NULL,
	`REGION_CODE`	VARCHAR(30)	NOT NULL
);


CREATE TABLE `CINEMA` (
	`CINEMA_NO`	INT	AUTO_INCREMENT PRIMARY KEY,
	`CINEMA_NAME`	VARCHAR(30)	NOT NULL,
	`REGION_NO`	INT	NOT NULL,
	`CINEMA_ADDR`	VARCHAR(50)	NOT NULL,
	`OPEN_TIME`	VARCHAR(50)	NOT NULL,
	`CLOSE_TIME`	VARCHAR(50)	NOT NULL
);

CREATE TABLE `GENRE` (
	`GENRE_NO`	INT AUTO_INCREMENT PRIMARY KEY,
	`GENRE_CONTENT`	VARCHAR(30)	NOT NULL
);

CREATE TABLE `MOVIE` (
	`MOVIE_NO`	INT	AUTO_INCREMENT PRIMARY KEY,
	`MOVIE_TITLE`	VARCHAR(30)	NOT NULL UNIQUE,
	`GENRE_NO2`	INT	NOT NULL,
	`POPULARITY`	DOUBLE,
	`DURATION`	INT	NOT NULL,
	`ORIGINAL_LANGUAGE`	VARCHAR(30),
	`MOVIE_CONTENT`	VARCHAR(255)	NOT NULL,
	`ADULT`	BOOLEAN	DEFAULT FALSE,
	`POSTER_PATH`	VARCHAR(255),
	`CREATE_DATE`	TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`MODFIY_DATE`	TIMESTAMP  ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE `SCREEN`;

CREATE TABLE `SCREEN` (
	`SCREEN_CODE`	VARCHAR(30)	PRIMARY KEY,
	`SCREEN_NAME`	VARCHAR(30)	NOT NULL,
	`TOTAL_SEAT_NUM`	INT	NOT NULL,
	`IS_AVAIL`	VARCHAR(30)	NOT NULL DEFAULT  'Y'
);


CREATE TABLE `SEAT` (
	`SEAT_NO`	INT	AUTO_INCREMENT PRIMARY KEY,
	`SEAT_NAME`	VARCHAR(30)	NOT NULL
);



CREATE TABLE `MOVIE_SCHEDULE` (
	`SCHEDULE_NO`	INT	AUTO_INCREMENT PRIMARY KEY,
	`MOVIE_NO`	INT	NOT NULL,
	`CINEMA_NO`	INT	NOT NULL,
	`SCREEN_CODE`	VARCHAR(30)	NOT NULL,
	`DATE`	VARCHAR(30)	NOT NULL,
	`START_TIME`	VARCHAR(30)	NOT NULL,
	`END_TIME`	VARCHAR(30)	NOT NULL
);

DROP TABLE `MOVIE_REVIEW`;

CREATE TABLE `MOVIE_REVIEW` (
	`REVIEW_NO`	INT	AUTO_INCREMENT PRIMARY KEY,
	`MOVIE_NO`	INT	NOT NULL,
	`MEMBER_NO`	INT	NOT NULL,
	`CONTENT`	VARCHAR(255)	NOT NULL,
	`RATE`	INT	NOT NULL,
	`CREATE_DATE` TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `CINEMA_AND_SCREEN` (
	`CINEMA_NO`	INT	 AUTO_INCREMENT,
	`SCREEN_CODE`	VARCHAR(30)	NOT NULL,
	PRIMARY KEY(`CINEMA_NO`, `SCREEN_CODE`)
);

DROP TABLE `CINEMA_AND_SCREEN`;


DROP TABLE `SCREEN_AND_SEAT`;

CREATE TABLE `SCREEN_AND_SEAT` (
	`SCREEN_CODE`	VARCHAR(30),
	`SEAT_NO`	INT	NOT NULL,
	PRIMARY KEY(`SEAT_NO`, `SCREEN_CODE`)
);


CREATE TABLE `RESERVATION` (
	`RSV_NO`	INT	AUTO_INCREMENT PRIMARY KEY,
	`SCHEDULE_NO`	INT	NOT NULL,
	`SEAT_NO`	INT	NOT NULL,
	`MEMBER_NO`	INT	NOT NULL,
	`RSV_MOVIE_PRICE`	INT	NOT NULL,
	`RSV_IS_PAID`	VARCHAR(2)	NOT NULL,
	`CREATE_DATE`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	`MODFIY_DATE`	TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



ALTER TABLE `CINEMA` ADD CONSTRAINT `FK_REGION_TO_CINEMA_1` FOREIGN KEY (
	`REGION_NO`
)
REFERENCES `REGION` (
	`REGION_NO`
);

ALTER TABLE `MOVIE` ADD CONSTRAINT `FK_GENRE_TO_MOVIE_1` FOREIGN KEY (
	`GENRE_NO2`
)
REFERENCES `GENRE` (
	`GENRE_NO`
);

ALTER TABLE `MOVIE_SCHEDULE` ADD CONSTRAINT `FK_MOVIE_TO_MOVIE_SCHEDULE_1` FOREIGN KEY (
	`MOVIE_NO`
)
REFERENCES `MOVIE` (
	`MOVIE_NO`
);

ALTER TABLE `MOVIE_SCHEDULE` ADD CONSTRAINT `FK_CINEMA_TO_MOVIE_SCHEDULE_1` FOREIGN KEY (
	`CINEMA_NO`
)
REFERENCES `CINEMA` (
	`CINEMA_NO`
);

ALTER TABLE `MOVIE_SCHEDULE` ADD CONSTRAINT `FK_SCREEN_TO_MOVIE_SCHEDULE_1` FOREIGN KEY (
	`SCREEN_CODE`
)
REFERENCES `SCREEN` (
	`SCREEN_CODE`
);

ALTER TABLE `MOVIE_REVIEW` ADD CONSTRAINT `FK_MOVIE_TO_MOVIE_REVIEW_1` FOREIGN KEY (
	`MOVIE_NO`
)
REFERENCES `MOVIE` (
	`MOVIE_NO`
);

ALTER TABLE `MOVIE_REVIEW` ADD CONSTRAINT `FK_MEMBER_TO_MOVIE_REVIEW_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);

ALTER TABLE `CINEMA_AND_SCREEN` ADD CONSTRAINT `FK_CINEMA_TO_CINEMA_AND_SCREEN_1` FOREIGN KEY (
	`CINEMA_NO`
)
REFERENCES `CINEMA` (
	`CINEMA_NO`
);

ALTER TABLE `CINEMA_AND_SCREEN` ADD CONSTRAINT `FK_SCREEN_TO_CINEMA_AND_SCREEN_1` FOREIGN KEY (
	`SCREEN_CODE`
)
REFERENCES `SCREEN` (
	`SCREEN_CODE`
);

ALTER TABLE `SCREEN_AND_SEAT` ADD CONSTRAINT `FK_SCREEN_TO_SCREEN_AND_SEAT_1` FOREIGN KEY (
	`SCREEN_CODE`
)
REFERENCES `SCREEN` (
	`SCREEN_CODE`
);

ALTER TABLE `SCREEN_AND_SEAT` ADD CONSTRAINT `FK_SEAT_TO_SCREEN_AND_SEAT_1` FOREIGN KEY (
	`SEAT_NO`
)
REFERENCES `SEAT` (
	`SEAT_NO`
);

ALTER TABLE `RESERVATION` ADD CONSTRAINT `FK_MOVIE_SCHEDULE_TO_RESERVATION_1` FOREIGN KEY (
	`SCHEDULE_NO`
)
REFERENCES `MOVIE_SCHEDULE` (
	`SCHEDULE_NO`
);

ALTER TABLE `RESERVATION` ADD CONSTRAINT `FK_SEAT_TO_RESERVATION_1` FOREIGN KEY (
	`SEAT_NO`
)
REFERENCES `SEAT` (
	`SEAT_NO`
);

ALTER TABLE `RESERVATION` ADD CONSTRAINT `FK_MEMBER_TO_RESERVATION_1` FOREIGN KEY (
	`MEMBER_NO`
)
REFERENCES `MEMBER` (
	`MEMBER_NO`
);






